DROP TABLE IF EXISTS user_scores;

CREATE TABLE user_scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user TEXT NOT NULL,
  song TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  perfect INTEGER NOT NULL,
  great INTEGER NOT NULL,
  good INTEGER NOT NULL,
  bad INTEGER NOT NULL,
  miss INTEGER NOT NULL,
  max_combo INTEGER NOT NULL,
  grade TEXT NOT NULL,
  plate TEXT NOT NULL,
  score INTEGER NOT NULL
);