import csv
import re
from pprint import pprint

def songs():
    songs = [
        '1950',
        '2006 Love Song',
        'A Site de la Rue',
        'Accident',
        'Achluoias',
        'Acquaintance',
        'Acquaintance (Full Song)',
        'Across the Ocean',
        'After School Stride',
        'Ai, Yurete...',
        'All I Want for Xmas',
        'Allegro con Fuoco',
        'Allegro Furioso',
        'Allegro PIU Mosso',
        'Amai Yuuwaku Dangerous',
        'Amphitryon',
        'Anguished Unmaking',
        'Annihilator Method',
        'Another Truth',
        'Arcane Force',
        'Arch of Darkness',
        'Arirang',
        "As If It's Your Last",
        'ASDF',
        'Asterios -ReEntry-',
        'Avalanche',
        'Avalanquiem (Remix)',
        'B.P. Classic Remix (Remix)',
        'B.P. Classic Remix 2 (Remix)',
        'B2',
        'Bad Apple!!',
        'Bad Apple!! (Full Song)',
        'Bad♾️End♾️Night',
        'Bang Bang Bang',
        'Bang Bang Bang (Full Song)',
        'BanYa Classic Remix (Remix)',
        'BanYa Hiphop Remix (Remix)',
        'BanYa-P Guitar Remix (Remix)',
        'Bar Bar Bar',
        'Bar Bar Bar (Full Song)',
        'Baroque Virus',
        'Be Alive',
        'Beat of the War',
        'Beat of the War 2',
        'Beat of the War 2 (Full Song)',
        'Beat the Ghost',
        'Beautiful',
        'Bedlam',
        'Bee',
        'Beethoven Influenza (Remix)',
        'Beethoven Virus',
        'Bemera (Remix)',
        'Bemera (Shortcut)',
        'Betrayer',
        'Betrayer -Act 2-',
        'Big Metra Remix (Remix)',
        'Blaze Emotion',
        'Blaze Emotion',
        'Blazing',
        'Boombayah',
        'Boombayah (Full Song)',
        'Break It Down',
        'Break Out',
        'Bring Back The Beat',
        "Bullfighter's Song",
        'Butterfly',
        'Campanella',
        'Cannon X.1',
        'Canon D',
        'Canon D (Full Song)',
        'Caprice of DJ Otada (Remix)',
        'Caprice of Otada',
        'Chase Me',
        'Chase Me (Full Song)',
        'Chicken Wing',
        'Chicken Wing (Shortcut)',
        'Chimera',
        'Chinese Restaurant',
        'Chopsticks Challenge',
        'Chopsticks Challenge (Full Song)',
        'Christmas Memories',
        'Chung Hwa Ban Jeom',
        'Cleaner',
        'Cleaner (Shortcut)',
        'Close Your Eyes',
        'Clue',
        "Com'back",
        'Come to Me',
        'Cosmic Rhythm',
        'Crashday',
        'Crashday (Full Song)',
        'Creed -1st Desire-',
        'Creed -1st Desire- (Full Song)',
        'Cross Over',
        'Cross Time',
        'Csikos Post',
        'D',
        'D Gang',
        'Dam',
        'Dance All Night',
        'Dance Vibrations',
        'Dance with Me',
        'Dawn of the Apocalypse',
        'Dawn of the Apocalypse (Full Song)',
        'Death Moon',
        'Death Moon (Shortcut)',
        'Deja Vu',
        'Deja Vu (Full Song)',
        'Destination',
        'Destination (Shortcut)',
        'Dieciséis',
        'Digan lo que Digan',
        'Digan lo que Digan (Full Song)',
        'DJ Otada',
        'Do It -Reggae Style-',
        'Do You Know That -Old School-',
        'Dolly Kiss',
        "Don't Bother Me",
        'Donatello',
        'Dr. KOA (Remix)',
        'Dr. M',
        'Dream to Nightmare',
        'Elise',
        'Elvis',
        'Elysium',
        'Emperor',
        'Energetic',
        'Energizer',
        'Enhanced Reality',
        'Everybody Got 2 Know (Remix)',
        'Exceed 2 Opening (Shortcut)',
        'EXTRA BanYa Remix (Remix)',
        'Extravaganza',
        'Extravaganza (Shortcut)',
        'Fallen Angel',
        'Faster Z',
        'Feel My Happiness',
        'FFF',
        'FFF (Shortcut)',
        'Final Audition',
        'Final Audition 2',
        'Final Audition 2 (Shortcut)',
        'Final Audition 3 UF',
        'Final Audition 3 UF (Shortcut)',
        'Final Audition Episode 1',
        'Final Audition Episode 2-1',
        'Final Audition Episode 2-2',
        'Final Audition Episode 2-X',
        'Final Audition Episode 2-X (Shortcut)',
        'First Love',
        'Flying Duck',
        'Follow Me',
        'Force of Ra',
        'Four Seasons of Loneliness ver.β',
        'Four Seasons of Loneliness ver.β (Full Song)',
        'Free Style',
        'Funky Tonight',
        'Further',
        'Gargoyle',
        'Get Up',
        'Get Up',
        'Get Your Groove On',
        'God Mode',
        'Good Night',
        'Gothic Resonance',
        'Gotta Be You',
        'Guitar Man',
        'Gun Rock',
        'Hard Core Mix (Remix)',
        'Hardkore of the North',
        "Hate, Don't Hate",
        'Heart Attack',
        'Heel and Toe',
        'Helix',
        'Hellfire',
        'Hello',
        'Hello William',
        'Her',
        'Hestia',
        'Hey U',
        'Hi-Bi',
        'Higgledy Piggledy',
        'HTTP',
        'Hungarian Dance V',
        'Hush',
        'Hush (Full Song)',
        'Hyacinth',
        'Hypercube',
        'Hyperion',
        'Hyperion (Shortcut)',
        'Hypnosis',
        'Hypnosis',
        "I'll Give You All My Love",
        "I'm Sorry",
        'Idealized Romance',
        'Ignis Fatuus',
        'Ignis Fatuus (Shortcut)',
        'Ignition Starts',
        'Imprinting',
        'Ineffective Boss Without Power',
        'Infinity',
        'Infinity RMX (Remix)',
        'Interference',
        'Interference (Full Song)',
        'J Bong',
        'Jackpot',
        "Jam O' Beat",
        "Jonathan's Dream",
        'Just Hold It',
        'Just Kiddin',
        'K.O.A.: Alice in Wonderworld',
        'K.O.A.: Alice in Wonderworld (Shortcut)',
        'Karyawisata',
        'Kasou Shinja',
        'Kasou Shinja (Shortcut)',
        'Katkoi',
        'Keep On!',
        'Kill Them!',
        'Ladybug',
        'Last Rebirth',
        'Latino Virus',
        'Le Grand Bleu',
        'Leakage Voltage',
        'Leather (Remix)',
        'Like Me',
        'Log In',
        'Loner',
        'Love Is a Danger Zone',
        'Love Is a Danger Zone',
        'Love Is a Danger Zone (Shortcut)',
        'Love Is a Danger Zone 2',
        'Love Is a Danger Zone 2',
        'Love Is a Danger Zone 2 (Full Song)',
        'Love Is a Danger Zone 2 (Shortcut)',
        'Love Is a Danger Zone: Try to B.P.M. (Remix)',
        'Lucid',
        'Mad5cience',
        'Magical Vacation',
        'Maria',
        'Matador',
        'Me Gustas Tu',
        'Me Gustas Tu (Full Song)',
        'Mental Rider',
        'Meteorize',
        'Midnight Blue',
        'Milky Way Galaxy',
        "Miss's Story",
        'Mission Possible',
        'Mission Possible -Blowback-',
        'Mitotsudaira',
        'Mobius Strip',
        'Moment Day',
        'Money',
        'Money Fingers (Remix)',
        'Monkey Fingers',
        'Monkey Fingers 2',
        'Monolith',
        'Moon Light Dance',
        'Moonlight',
        'Moonlight (Shortcut)',
        'Move That Body!',
        'Move That Body! (Full Song)',
        'Move That Body! (Shortcut)',
        'Mr. Larpus',
        'msgoom RMX pt. 3 (Remix)',
        'msgoon RMX pt. 1 (Remix)',
        'msgoon RMX pt. 5 (Remix)',
        'msgoon RMX pt. 6 (Remix)',
        'My Dreams',
        'My Way',
        'N',
        'Naissance',
        'Naissance 2',
        'Nakakapagpabagabag',
        'Napalm',
        'Narcisista por Excelencia',
        'Narcisista por Excelencia (Full Song)',
        'Native',
        'Necromancy',
        'Nemesis',
        'Nightmare',
        'Nina PXNDX Remix (Remix)',
        'NoNoNo',
        'NoNoNo (Full Song)',
        'Number Nine',
        'NX Opening (Shortcut)',
        'Oh! Rosa',
        'On and On',
        'One',
        'Online',
        'Overblow',
        'Overblow (Shortcut)',
        'Overblow 2',
        'Oy Oy Oy',
        'Pandora',
        'Pandora (Full Song)',
        'Papa Gonzales',
        'PaPa Helloizing (Remix)',
        'PARADOXX (Remix)',
        'Passacaglia',
        'Passacaglia (Shortcut)',
        'Passing Rider',
        'Pavane',
        'Pañuelito Rojo',
        'Pañuelito Rojo (Full Song)',
        'Phantom',
        'Phantom -Intermezzo-',
        'Pick Me',
        'Pick Me',
        'Pine Nut',
        'Point Break',
        'Point Zero One',
        'Pop the Track',
        'Pop the Track (Shortcut)',
        'Prime',
        'Prime 2 Opening (Shortcut)',
        'PRIME Opening (Shortcut)',
        'PRO Pop Remix (Remix)',
        'Procedimientos Para Llegar a un Común Acuerdo',
        'Procedimientos Para Llegar a un Común Acuerdo (Full Song)',
        'Procedimientos Para Llegar a un Común Acuerdo (Shortcut)',
        'Pump Jump',
        'Pump Me Amadeus',
        'Pumping Jumping',
        'Pumping Up',
        'Pumptris 8bit ver.',
        'Pumptris 8bit ver. (Shortcut)',
        'Pumptris Quattro',
        'Queen of the Red',
        'Ragnarok',
        'Rainspark',
        'Rave Until the Night Is Over',
        "Rave'till the Earth's End",
        'RE-RAVE',
        'Reality',
        'Really Really',
        'Red Snow',
        'Red Swan',
        'Redline',
        'Reminiscence',
        'Removable Disk0',
        'Requiem',
        'Rhythm Ta',
        "Rippin' It Up",
        'Robot Battle',
        'Rock the House',
        'Rock the House (Shortcut)',
        'Rockhill',
        'Rolling Christmas',
        'Sarabande',
        'Sarabande (Shortcut)',
        'Seize My Day',
        'Selfishness',
        'Selfishness (Shortcut)',
        'Set Me Up',
        'Set Up Me2 Mix (Remix)',
        'Setsuna Trip',
        'She Likes Pizza',
        'Shub Niggurath',
        'Shub Niggurath (Shortcut)',
        'Shub Sothoth (Remix)',
        'Sik Asik',
        'Silhouette Effect',
        'Silhouette Effect (Shortcut)',
        'Silver Beat',
        'Slam',
        'Smells Like a Chocolate',
        'Smile Diary',
        'Sober',
        'Solitary',
        'Solitary 1.5',
        'Solitary 2',
        'Solitary 2 (Shortcut)',
        'Sora no Shibane',
        'Sorceress Elise',
        'Star Command',
        'Stardust Overdrive',
        'Stardust Overdrive (Shortcut)',
        'Start on Red',
        'Step',
        'Street Show Down',
        'Sudden Romance',
        'Sugar Conspiracy Theory',
        'Sugar Eyes',
        'Sugar Free',
        'Sugar Free (Full Song)',
        'Super Capriccio',
        'Super Fantasy',
        'Super Fantasy (Shortcut)',
        'Super Magic',
        "Super Stylin'",
        'Switchback',
        'Systemization',
        'Take Me Back',
        'Take Out',
        'Take Out (Shortcut)',
        'Techno Repeatorment (Remix)',
        'Tek -Club Copenhagen-',
        'Tepris',
        'The Devil',
        'The Festival of Ghost',
        "The People Didn't Know",
        'The People Didn\'t Know "Pumping Up" (Remix)',
        'The Quick Brown Fox Jumps Over the Lazy Dog',
        'The Revolution',
        'Till the End of Time',
        'Time Attack <Blue>',
        'Toccata',
        'Top City',
        'Trashy Innocence',
        'Trato de No Trabarme (Full Song)',
        'Travel to Future',
        'Tream Vook of the War (Remix)',
        'Tribe Attacker',
        'Tritium',
        'Trotpris (Shortcut)',
        'Turkey March -Minimal Tunes-',
        'Turkey Virus (Remix)',
        'Twist of Fate',
        'U Got 2 Know',
        'U Got Me Crazy',
        'U Got Me Rocking',
        'U Got Me Rocking (Shortcut)',
        'Ugly Dee',
        'Unique',
        'Unique (Shortcut)',
        'Up & Down',
        'Up & Down (Full Song)',
        'Up & Up',
        'Utopia',
        'Utsushiyo No Kaze',
        'V3',
        'Vacuum',
        'Vacuum Cleaner (Remix)',
        'Venus',
        'Very Good',
        'video out c',
        'Violet Perfume',
        'Virtual Emotion',
        'Visual Dream II',
        'Vook',
        'Vulcan (Remix)',
        'VVV',
        'We Got 2 Know',
        'We Will Meet Again',
        'What Are You DOIN? (Remix)',
        'What Happened',
        'Wi-Ex-Doc-Va (Remix)',
        "Will-o'-the-wisp",
        'Windmill',
        'Winter',
        'Winter (Shortcut)',
        'Witch Doctor',
        'Witch Doctor #1',
        'Witch Doctor (Shortcut)',
        'X-Rave',
        'X-Rave (Shortcut)',
        'X-Tree',
        'X-Treme',
        'Xenesis',
        'Xuxa',
        'Y2Z',
        'Yeo Rae A',
        'Yog Sothoth',
        'Yog Sothoth (Shortcut)',
        'Yoropiku Pikuyoro',
        'You Again My Love',
        "You're the Best"
    ]

def process_csv(filename, label=None):
    songs = []
    with open(filename, 'r', encoding='utf-8') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header row
        for row in reader:
            if len(row) > 1:
                song_name = row[1].strip()
                # Remove content within parentheses and square brackets
                song_name = re.sub(r'\s*[\(\[].*?[\)\]]', '', song_name)
                if label:
                    song_name += f" ({label})"
                songs.append(song_name)
    return songs

def main():
    all_songs = []
    
    # Process each CSV file
    all_songs.extend(process_csv('arcade.csv'))
    all_songs.extend(process_csv('full_song.csv', 'Full Song'))
    all_songs.extend(process_csv('shortcut.csv', 'Shortcut'))
    all_songs.extend(process_csv('remix.csv', 'Remix'))
    
    # Sort the list alphabetically
    all_songs.sort(key=str.lower)
    
    # First item is '' so remove it
    all_songs.pop(0)
    
    # Print the sorted list
    pprint(all_songs)

if __name__ == "__main__":
    main()

